<a href="https://colab.research.google.com/github/TinkerTechie/NeuralNetwork/blob/main/Copy_of_Neural_Network_4Steps_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1: - Data Definition**

In [35]:
import numpy as np

# Define learnable training and validation data in two simple lines
xtrain = np.random.rand(5000, 32) * 10
xval = np.random.rand(1000, 32) * 10

ytrain = (xtrain[:, :5] * 2) + (np.random.randn(5000, 5) * 0.5)
yval = (xval[:, :5] * 2) + (np.random.randn(1000, 5) * 0.5)

**Step 2:- Define the Neural Network Model**

In [36]:
from keras import models, layers

In [37]:
model = models.Sequential()

In [38]:
model.add(layers.Dense(16,input_dim=32))
model.add(layers.Dense(5))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**Step 3 :- Compile Your Neural Network Model**

In [39]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 5)              │            85 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 613 (2.39 KB)

 Trainable params: 613 (2.39 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
from keras.optimizers import SGD
model.compile(optimizer =SGD(learning_rate=0.001),loss='mse',metrics=['mae'])

**Step 4: - Train your Neural Network Model**

In [46]:
model.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2608 - mae: 0.4077
Epoch 2/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2618 - mae: 0.4076
Epoch 3/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2603 - mae: 0.4069
Epoch 4/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2635 - mae: 0.4089
Epoch 5/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2611 - mae: 0.4081
Epoch 6/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2578 - mae: 0.4048
Epoch 7/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2583 - mae: 0.4064
Epoch 8/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2608 - mae: 0.4079
Epoch 9/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2543 - mae: 0.4007
Epoch 10/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2616 - mae: 0.4081
Epoch 11/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2620 - mae: 0.4083
Epoch 12/100
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2638 - mae: 0.4091
Epoch 13/100


In [47]:
xval

array([[7.83423171, 7.92379839, 9.10787453, ..., 7.44263365, 2.86495854,
        0.83702889],
       [7.71201284, 8.39679708, 7.7023276 , ..., 3.76487201, 9.92396995,
        0.65026269],
       [4.67170443, 7.87607928, 5.81712168, ..., 6.02731277, 5.04405982,
        8.03638606],
       ...,
       [9.2512999 , 2.36454426, 1.9896648 , ..., 9.49162444, 9.26625677,
        7.05305013],
       [5.94805658, 1.95560177, 0.80291739, ..., 0.6061851 , 3.82541169,
        3.54764813],
       [0.40314588, 4.60859438, 5.96642711, ..., 9.83786779, 7.17867912,
        8.87019301]])

In [48]:
xval[100]

array([1.20270308, 4.46401221, 5.37592697, 1.4590558 , 3.11210494,
       8.49342994, 7.14553387, 0.97898324, 9.52759537, 5.13123828,
       3.47993183, 4.78242156, 7.38628361, 1.70916643, 1.46729217,
       3.95016946, 6.7982126 , 8.11954141, 4.54392973, 6.86850699,
       5.39751766, 8.55974163, 8.238061  , 5.09148275, 6.86355865,
       8.64686531, 3.2439178 , 5.08141574, 5.38883945, 4.47020308,
       0.174396  , 8.75059224])

In [51]:
print(model.predict(xval[100].reshape(1,32)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[ 2.3980134  8.968089  10.718128   2.8149378  6.3088803]]
